//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosClaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recargas
    {
        public int Id { get; set; }
        public string Lugar { get; set; }
        public decimal Precio { get; set; }
        public string Celular { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Tarea { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Tareas Tareas { get; set; }
    }
}
