//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosClaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasEmpleados
    {
        public int Id { get; set; }
        public Nullable<int> Tarea { get; set; }
        public Nullable<int> Empleado { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Tareas Tareas { get; set; }
    }
}
